# Generated by Django 2.2.3 on 2018-01-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180129_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completion_date',
            field=models.DateField(null=True),
        ),
    ]
